### PR TITLE
Handle spaces and quotes in the filename

### PR DESCRIPTION
**Pull request by lmarburger**
Spaces or quotes in a filename would silently do nothing. Calling `#inspect` on the output path fixes the few scenarios I tested.

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for the pull request!
Although, there are a few problems :-)

`buffer.name` on [L#36](https://github.com/robgleeson/hammer.vim/pull/13/files#L0R36) needs to be escaped, too, as it is a absolute path to the buffer on disk. 
`Vim::Buffer#name` comes from the Ruby bindings for Vim, and it is a pretty non-descript name I gotta admit.

I think instead of `#inspect`, we should be using `Shellwords.escape` from the Ruby standard library. 
The `Hammer::ENV.browser` method can also return a full path so that'd need escaped too.

If you feel up to it, you can hack on it yourself. If not, I'll get around to it tonight when I have some time. :-)

**Comment by lmarburger** [comment]
Didn't know about Shellwords.escape. That seems much more appropriate. Nice!

I probably would've noticed `buffer.name` 3 lines below but I wasn't working in that conditional. I'll hack on this shortly and send another pull request.

**Comment by lmarburger** [comment]
There we go. Both `browser` and `output_path` are using `Shellwords.escape`. Pretty slick method. Can't believe I haven't seen it before.

**Comment by ghost** [comment]
Looks good, thanks!

**Pull request merged**
