### PR TITLE
Fix issue #19

### PR DESCRIPTION
**Pull request by sagebomb**

### CODE REVIEW

**Comment by ghost** [comment]
I think we could namespace the filename we write to: `<filename>.pygments` - what do you think?

**Comment by sagebomb** [comment]
Good idea. And you will try call :Hammer from console Vim? My gvim works perfectly, but vim freeze for a time and result of a `pygmentize` output to stdout (in terminal, instead of vim).

**Comment by ghost** [comment]
Yeah, console vim works okay here, but I made a few changes - `-o` option seemed to be missing, so the output generated by `pygmentize` would end up in $stdout. Could you give the latest changes on the branch a try? Much appreciated!

**Comment by sagebomb** [comment]
Good job! Awesome! Also, my commit does not work (i not use -o option, and read to `text` old file, without `pygmentize`), sorry, i write fix at 5:00 AM in Moscow time :-)

**Comment by ghost** [comment]
No worries, thanks for the fix!

**Comment by sagebomb** [comment]
Thanks for awesome plugin!

**Pull request merged**
